version: 0.0
os: linux
hooks:
  BeforeInstall:
    - location: deploy/scripts/run-ansible-deploy.sh
      timeout: 600
      runas: root
  AfterInstall:
    - location: deploy/scripts/run-ansible-deploy.sh
      timeout: 600
      runas: root
  ApplicationStart:
    - location: deploy/scripts/run-ansible-deploy.sh
      timeout: 600
      runas: root
  ValidateService:
    - location: deploy/scripts/run-ansible-deploy.sh
      timeout: 300
      runas: root
